Sustainable days
issuefab/model pull request #110
Opened 2023-08-31 14:30 UTC by EliasEriksson

2023-08-31 14:36 UTC, EliasEriksson reviewed
self check

2023-08-31 14:36 UTC, EliasEriksson commented on Cadence/index.ts
> +	}
rename the one letter variables

2023-08-31 14:36 UTC, EliasEriksson commented on CostCenter/index.ts
> +	// validation must chest that all children occurs after created date
This will be fixed by this issue https://github.com/issuefab/app/issues/250

2023-08-31 14:36 UTC, EliasEriksson commented on Cadence/index.ts
> +	function dayDiff(first: isoly.Date | isoly.DateTime, other: isoly.Date | isoly.DateTime): number {
rename this function

2023-09-01 06:03 UTC, TheLillyleaf requested changes
minor things.

2023-09-01 06:03 UTC, TheLillyleaf commented on Cadence/index.ts
> +		//
remove lines

2023-09-01 06:34 UTC, EliasEriksson commented on Cadence/index.ts
>  		interval: isly.union(isly.string("year"), isly.string("month"), isly.string("week"), isly.string("single")),
required for the sustain function. maybe ill should source the intervals from elsewhere.

2023-09-01 06:58 UTC, EliasEriksson commented on Cadence/index.ts
>  		interval: isly.union(isly.string("year"), isly.string("month"), isly.string("week"), isly.string("single")),
never mind. i only needed it for testing

2023-09-01 07:26 UTC, EliasEriksson reviewed
self check

2023-09-01 07:29 UTC, TheLillyleaf approved these changes

2023-09-01 07:30 UTC, merged