Add paid
issuefab/model pull request #90
Opened 2023-06-05 12:01 UTC by TheLillyleaf

2023-06-05 12:04 UTC, TheLillyleaf reviewed
self check

2023-06-05 12:18 UTC, EliasEriksson reviewed
Maybe its time to take the setp you have been talking about? should we make a new Folder on the top level in the model called repport with Expence and Receipt repports? then we could have the API request type be `Repport.Expense.Creatable` / `Repport.Receipt.Creatable` and response could be `Repport.Expense` / `Repport.Receipt`. we could also moteh the apropriate compile function into those type away from receipt / purchase(?)

2023-06-05 12:18 UTC, EliasEriksson commented on Purchase/index.ts
> +
github gives automatic warning here. run `npm run lint`

2023-06-05 12:18 UTC, EliasEriksson commented on Purchase/index.ts
> +		compileData: Record<string, { purpose: string; date: isoly.Date; amount: Amount }[]>,
do we maybe want to extract these types to some Creatable of something? they are used in the API quite a lot as well if i am not mistaken?

2023-06-08 09:36 UTC, TheLillyleaf reviewed
self check

2023-06-08 09:47 UTC, EliasEriksson requested changes
only few small things

2023-06-08 09:47 UTC, EliasEriksson commented on Report/Creatable.ts
> +	const type = isly.union(ReportExpense.Creatable.type, ReportReceipt.Creatable.type)
dont forget the type argument
`isly.union<Creatable>(...)`

2023-06-08 09:47 UTC, EliasEriksson commented on Payment/Expense/Paid.ts
> +	export function is(value: Paid | any): value is Paid {
rewrite with isly

2023-06-08 09:47 UTC, EliasEriksson commented on Report/Expense/index.ts
> +	file: Uint8Array
Just making sure. this is supposed to be `Uint8Array` and not `File` ?

2023-06-09 06:15 UTC, closed without merging