CostCenter.Creatable
issuefab/model pull request #91
Opened 2023-06-08 14:24 UTC by EliasEriksson

* added interface for `CostCenter.Creatable`
* copied over types and function from `Delegation` to a new interface/type `CostCenter`
* any is functions the new types were based on were converted to `isly`

2023-06-08 14:35 UTC, EliasEriksson reviewed
minifixes

2023-06-08 14:35 UTC, EliasEriksson commented on CostCenter/index.spec.ts
> +		expect(typeof issuefab.CostCenter.validate).toEqual("function")
check equality with delegation instead

2023-06-08 14:35 UTC, EliasEriksson commented on Delegation/index.ts
> +
remove

2023-06-09 05:59 UTC, TheLillyleaf requested changes
Small stuff

2023-06-09 05:59 UTC, TheLillyleaf commented on CostCenter/Creatable.ts
> +		amount: Amount.type,
Snyggt! Så alla typer vi har som finns i modellen är bara att köra så, det får en ju att vilja skriva om dom vi använder.

2023-06-09 05:59 UTC, TheLillyleaf commented on Delegation/Data/index.ts
>  import * as isoly from "isoly"
Lägg till ny import

2023-06-09 05:59 UTC, TheLillyleaf commented on Delegation/index.ts
>  import * as isoly from "isoly"
Ny import

2023-06-09 06:41 UTC, EliasEriksson commented on CostCenter/Creatable.ts
> +		amount: Amount.type,
yes. skrev om dom som jag kom i kontakt med i denna PR

2023-06-09 06:45 UTC, TheLillyleaf commented on CostCenter/Creatable.ts
> +		amount: Amount.type,
Jag fortsätter med det, då jag komemr ha både purchase och receipt osv.

2023-06-09 06:46 UTC, TheLillyleaf approved these changes

2023-06-19 06:56 UTC, TheLillyleaf reviewed
Small things

2023-06-19 06:56 UTC, TheLillyleaf commented on CostCenter/index.ts
> +	from: string
finns i creatable

2023-06-19 06:56 UTC, TheLillyleaf commented on CostCenter/Creatable.ts
> +	purpose?: string
Vad är skillnaden mellan purpose och Costcenter?

2023-06-19 06:56 UTC, TheLillyleaf commented on CostCenter/index.spec.ts
> +	it("create", () => {
Kanske ett failande test också ?

2023-06-19 06:56 UTC, TheLillyleaf commented on Delegation/find.ts
> +// add test for this one
Was test added?

2023-06-19 06:56 UTC, TheLillyleaf commented on Payment/Card/Details.ts
> +	// }
remove

2023-06-19 06:56 UTC, TheLillyleaf commented on Payment/Card/index.ts
> +export interface Card extends CardCreatable {
Card.Creatable

2023-06-19 06:56 UTC, TheLillyleaf commented on Payment/PrePaid/index.spec.ts
> +		expect(issuefab.Payment.PrePaid.Creatable.is({ ...prePaid, wrong: "should become false" })).toEqual(true)
This should fail!

2023-06-19 06:56 UTC, TheLillyleaf commented on Purchase/index.ts
> +export interface Purchase extends PurchaseCreatable {
Purchase.Creatable

2023-06-19 07:11 UTC, EliasEriksson commented on CostCenter/Creatable.ts
> +	purpose?: string
costCenter = cost centrets namn
purpose = Description men för backwards compatability heter propertyn intern fortfarande purpose

2023-06-19 11:13 UTC, TheLillyleaf approved these changes

2023-06-19 15:02 UTC, merged